// strings/en.js — the COMPLETE reference UI string table. All other language
// tables fall back to these keys. Keep keys grouped by area and stable; never
// delete a key without removing its use.
export default {
  // brand / chrome
  "brand.name": "RTI Setu",
  "brand.tagline": "सत्यमेव जयते · Truth alone prevails",
  "foot.act": "सत्यमेव जयते · RTI Act, 2005",
  "common.back": "← Back",
  "common.backShort": "Back",
  "common.next": "Continue",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.optional": "optional",
  "common.required": "required",

  // top bar
  "nav.history": "My RTIs",
  "nav.newRti": "New RTI",
  "nav.language": "Language",
  "lang.soon": "coming soon",
  "nav.details": "My details",

  // gamebar
  "game.civicXp": "Civic XP",
  "game.dayStreak": "Day streak",
  "game.noBadge": "No badge yet",
  "game.fileFirst": "File your first RTI to begin",
  "game.locked": "??? — file one RTI to reveal",
  "game.sealedSub": "Sealed honour · file 1 RTI to reveal",
  "game.typingPrefix": "",

  // progress rail
  "rail.choose": "Choose",
  "rail.write": "Write",
  "rail.check": "Check",
  "rail.file": "File",

  // language screen
  "lang.heading": "Choose your language",
  "lang.sub": "You can change this any time. This changes the app, not the language of the RTI you file.",

  // landing (category-led)
  "landing.heading": "What do you want to know?",
  "landing.sub": "Pick a topic and we'll help you write a proper Right to Information request — for free.",
  "landing.selfWrite": "I'll write it myself",
  "landing.noneFit": "None of these fit? → Write your own RTI",
  "landing.getHelp": "Help me draft it",
  "landing.getHelpSoon": "Drafting help is coming soon. For now, pick a topic or write it yourself.",
  "landing.free": "Free · no account needed",

  // categories
  "cat.education": "Education & exams",

  // template picker
  "pick.heading": "Which situation fits best?",
  "pick.sub": "Choose the closest match. You can edit every word afterwards.",
  "pick.routing": "Where this goes",

  // blanks wizard
  "blank.progress": "Question {n} of {total}",
  "blank.requiredErr": "Please fill this in to continue.",
  "blank.selectPlaceholder": "Tap to choose",

  // authority autocomplete
  "authority.heading": "Which authority should receive this?",
  "authority.sub": "Start typing the ministry or department name and pick the official match.",
  "authority.placeholder": "Ministry or department name",
  "authority.matchOk": "✓ Matches an official ministry",
  "authority.matchWarn": "⚠ Not on the official list — the portal may reject this",

  // editor (hero)
  "editor.heroHeader": "This is your actual RTI — the exact words that will be filed.",
  "editor.sub": "Read it. Change anything you like. Nothing is sent until you choose to file.",
  "editor.ministryLabel": "This will be filed with:",
  "editor.changeMinistry": "Change ministry",
  "editor.restored": "Draft restored from your last session.",
  "editor.charCountOk": "✓ Within the 3000-character limit",
  "editor.charCountOver": "✗ Over the 3000-character limit — trim it before filing",
  "editor.readAloud": "🔊 Read it aloud",
  "editor.stopAloud": "■ Stop",
  "editor.toVerify": "Looks right — continue",
  "editor.empty": "Write your RTI here. Ask for specific documents and records — not opinions or reasons.",

  // state-level warning (gentle "worth checking" framing — NOT "you made an error")
  "state.heading": "Worth a quick check",
  "state.body": "Part of this might be handled by a State Information Commission rather than the central portal. It's often perfectly fine to file here — just take a moment to confirm your subject is a central-government matter before you send it.",

  // verification gate
  "verify.heading": "Let's check before you file",
  "verify.askingFor": "You are asking for:",
  "verify.warningsTitle": "Worth a look",
  "verify.asksNote": "These are suggestions to help you check — tick the ones that match. They don't change your RTI.",
  "verify.appealTitle": "If part of it is refused, you can appeal",
  "verify.appealLead": "That's normal for a strong RTI — and a first appeal is free. Here's what might come up:",
  "verify.decisionPrompt": "If this says what you mean, continue. Otherwise go back and edit it.",
  "verify.correct": "This is correct → Continue",
  "verify.edit": "Edit the RTI",

  // applicant details
  "details.heading": "Your details",
  "details.sub": "Saved on this device and pre-filled onto the portal form. Sent only to rtionline.gov.in when you file.",
  "details.name": "Full name (as on your ID)",
  "details.address": "Complete postal address",
  "details.email": "Email",
  "details.emailConfirm": "Confirm email (catches typos)",
  "details.mobile": "Mobile (optional)",
  "details.bplLabel": "Below Poverty Line (BPL) card?",
  "details.bplNo": "No — I'll pay the ₹10 fee",
  "details.bplYes": "Yes — fee is waived",
  "details.err": "Address and email are required.",
  "details.continue": "Continue",

  // ready to file
  "ready.heading": "Ready to file",
  "ready.sub": "Your RTI is saved. Open the RTI Setu button in your browser toolbar and press “Fill the portal form now.”",
  "ready.openPopupNote": "Open the RTI Setu toolbar button → “Fill the portal form now”. We'll fill the portal form for you.",
  "ready.lastMileTitle": "The last step needs a person",
  "ready.lastMileBody": "On the portal, a ministry box will be highlighted in orange. Type the security code (CAPTCHA) you see, then pay the ₹10 fee and press Submit. We never do this part for you — it needs eyes and a payment method.",
  "ready.lastMileHelp": "If reading the code or paying is hard, ask a family member to help with just this final step.",
  "ready.fee": "Filing fee",
  "ready.feeAmt": "₹10 (waived for BPL cardholders)",
  "ready.deadline": "By law you should get a reply within 30 days.",
  "ready.fileAnother": "Start another RTI",
  "ready.readAloud": "🔊 Hear the full RTI",
  "ready.markFiled": "I've filed it — track it",
  "ready.filedConfirmQ": "Have you already completed the CAPTCHA, paid the ₹10, and pressed Submit on the portal? Marking it filed closes this draft.",
  "ready.yesFiled": "Yes, it's filed",
  "ready.notYet": "Not yet — keep the draft",

  // file screen (the "File" step — two columns on desktop)
  "file.heading": "File your RTI",
  "file.summaryTitle": "Filing summary",
  "file.kvApplicant": "Applicant",
  "file.kvLength": "RTI length",
  "file.kvDraftSaved": "Draft saved",
  "file.kvDraftSavedVal": "On this device",
  "file.whatHappens": "What will happen",
  "file.step1": "Opens rtionline.gov.in in a new tab",
  "file.step2": "Clicks past the guidelines page automatically",
  "file.step3": "Fills the ministry, your name, address, email, mobile and RTI text",
  "file.step4": "Pauses at the CAPTCHA — you solve it yourself",
  "file.step5": "You pay the ₹10 fee and press Submit",
  "file.vault": "Your draft is safe — it stays on this device until you mark it filed. If the portal crashes, times out, or loses your session, come back and re-fill instantly.",
  "file.refillTitle": "Portal timed out or dropped your form?",
  "file.refill": "Re-fill",
  "file.ceremonyBig": "File your RTI",
  "file.ceremonySub": "You are legally demanding information from the state. This matters.",
  "file.captchaTitle": "CAPTCHA — you solve this",
  "file.captchaBody": "When the form opens, the security-code box is outlined in orange. Type the characters you see, then pay the ₹10 and press Submit. We never solve it for you — that's deliberate.",
  "file.captchaHint": "← outlined in orange",
  "file.security": "Form data is wiped from session storage the moment the form is filled. Your draft stays on this device until you clear it.",
  "file.openPortal": "Open portal and auto-fill",
  "file.backToEdit": "Edit the RTI",

  // filing screen (combined: portal-loading factoids + registration-number entry)
  "filing.title": "Navigating the portal",
  "filing.sub": "The government site is opening in a new tab. This can take 8–15 seconds. Your draft is safe.",
  "filing.dykLabel": "Did you know",
  "filing.tip1": "Departments must reply within 30 days by law.",
  "filing.tip2": "BPL cardholders file for free — no ₹10 fee.",
  "filing.tip3": "Officers can face a ₹250/day penalty for delays.",
  "filing.tip4": "You cannot be asked why you want the information.",
  "filing.refTitle": "After you submit on the portal",
  "filing.refBody": "The portal shows a registration number once your RTI is submitted (and emails it to you). Enter it here to confirm your filing and earn your Civic XP.",
  "filing.refLabel": "RTI registration number",
  "filing.refPlaceholder": "e.g. MOEFCC/R/2026/00421",
  "filing.confirm": "Confirm filing",
  "filing.refErr": "Enter the registration number the portal gave you.",
  "filing.awaiting": "It'll arrive by email — track it without the number for now",
  "filing.reopenPortal": "Re-open the portal",

  // postgame (ceremonial — civic honour, no confetti)
  "postgame.filed": "RTI filed",
  "postgame.refLine": "Registration no. {ref}",
  "postgame.gained": "+{n} XP this filing",
  "postgame.medalsTitle": "Your honours",
  "postgame.earnedNow": "Earned now",
  "postgame.lockedMore": "{n} more {track} RTIs",
  "perk.syncT": "Cross-device sync",
  "perk.syncS": "File from phone or laptop",
  "perk.boardT": "Honour roll",
  "perk.boardS": "City · state · national",
  "perk.trackerT": "Response tracker",
  "perk.trackerS": "30-day deadline alerts",
  "perk.networkT": "RTI network",
  "perk.networkS": "See what others file",
  "postgame.nextIn": "Lv {lvl} → Lv {next} · {name} in {xp} XP",
  "postgame.maxLevel": "Highest rank reached · {name}",
  "postgame.loginHeadline": "Keep your record across devices",
  "postgame.loginSub": "Your XP and honours are saved on this device. Create a free account to sync across devices and take your place on the civic honour roll.",
  "postgame.loginBtn": "Create free account · join the honour roll",
  "postgame.skip": "No thanks — keep it on this device",
  "postgame.localNote": "Your XP and honours are already saved here. Nothing is lost if you skip — you can create an account any time.",
  "postgame.another": "File another RTI",
  "postgame.toHistory": "Go to My RTIs",

  // history
  "history.heading": "My RTIs",
  "history.empty": "No RTIs yet. Your filings will appear here with their 30-day reply deadlines.",
  "history.overview": "Overview",
  "history.statFiled": "RTIs filed",
  "history.statReplies": "Replies in",
  "history.statAppeals": "Appeals",
  "history.statXp": "Civic XP",
  "history.tracks": "Tracks",
  "history.all": "All RTIs",
  "history.resumeTitle": "You have a draft in progress",
  "history.resume": "Continue your draft",
  "history.ref": "Ref: {ref}",
  "history.addRef": "Add registration number",
  "history.refSave": "Save",
  "history.status.pending": "Awaiting reply",
  "history.status.awaiting_ref": "Awaiting reference",
  "history.status.received": "Reply received",
  "history.status.appeal": "Appeal filed",
  "history.daysLeft": "{n} days left to reply",
  "history.overdue": "Reply overdue — you can file a free first appeal",
  "history.markReceived": "Mark reply received",
  "history.fileAppeal": "File first appeal",
  "history.honorTitle": "Civic honour roll",
  "history.honorTeaser": "Create a free account to take your place on the civic honour roll — city, state and national registers of citizens who hold power to account.",
  "history.honorBtn": "Create free account",

  // validity warnings (mirrors validity.js ids; the engine message is shown, these are titles)
  "validity.too_short": "This RTI looks very short.",
  "validity.unresolved": "Some blanks weren't filled in.",
  "validity.opinion": "This may be asking for an opinion.",
  "validity.duplicate": "Similar to one you already filed."
};
